### ISSUE TITLE
Utility to create table/ columns / row and use it to build a basic demo on tree.html

### ISSUE THREAD

**Issue by SamyPesse** [mitermayer/draft-js#1]
`NestedUtil` can have some utility functions to manage tables:

``` js
// Create a new table / Convert current block as a table (2x2)
NestedUtil.insertTable(editorState: EditorState, rows: Number, columns: Number) -> EditorState

// Insert a new row in the table
NestedUtil.insertRow(editorState: EditorState) -> EditorState

// Insert a new column in the table
NestedUtil.insertCoumn(editorState: EditorState) -> EditorState
```

**Comment by mitermayer** [comment]
I Think tables should be a component on its own maybe not part of nestedUtils as nestedUtils should be a bit more generic function for dealing with blocks that have nested blocks. what do you reckon ?

**Comment by SamyPesse** [comment]
Yes, it makes sense, do you think it should still be in Draft (like a `TableUtil`?) or has an "external" component?

**Comment by mitermayer** [comment]
I think at first we should just include the 'TableUtil' as an example component on the tree.html. This way we don't need to fully implement all functionality and later on we can extract it either to a plugin or to another part in core. 

TableUtil would leverage from the NestedUtil

**Comment by mitermayer** [comment]
I think once we get the editorState to raw we can start on this one

**Comment by mitermayer** [comment]
@SamyPesse  maybe we should add table examples a bit later to reduce the size of this PR.

**Comment by mitermayer** [comment]
Lets not do tables for this PR since it has almost everything in there
