### ISSUE TITLE
[bug] Cells and Rows should not create new elements when pressing enter

### ISSUE THREAD

**Issue by mitermayer** [mitermayer/draft-js#10]
Maybe not entirely related to tree block structure but pressing ENTER on a cell or on td is currently creating a new block.

**Comment by SamyPesse** [comment]
It depends if the cells are end block or block container. For the GitBook Editor, we'll be using cells as end block (only contains inline styles and entities).

It doesn't really depend on draft, only the `blockRendererMap` and the initial ContentState input.

**Comment by SamyPesse** [comment]
@mitermayer Closing this since it only depends on the configuration.
