### ISSUE TITLE
parentBlockRenderingConfig is not really necessary in convertFromRawToDraftState

### ISSUE THREAD

**Issue by SamyPesse** [mitermayer/draft-js#11]
@mitermayer This issue is related to this [line](https://github.com/SamyPesse/draft-js/blob/feature/tree/src/model/encoding/convertFromRawToDraftState.js#L57).

I don't think we need to use `parentBlockRenderingConfig` in `convertFromRawToDraftState`, it makes the function signature longer and require to have access to the blockRenderMap when we are converting data (in our case: we are converting data in the store and creating the right `blockRenderMap` in the react views).

I think we should trust the input data, and juste convert it as it.

Since this is not being used during copy/pasting, it should not cause any trouble.

**Comment by mitermayer** [comment]
We would still need it in there to guarantee we only add blocks that we support, otherwise people may be able to select this elements later and try to paste it on another section of the document just to get it flattened

**Comment by SamyPesse** [comment]
I'm only talking about the `convertFromRawToDraftState`, which is only used explicitly by the developer, I agree the HTMl conversion should keep access to the `blockRenderMap`.

But in the case of `convertFromRawToDraftState`, it complexifies the use of this method, when we should just trust the input data (same thing for `convertFromDraftToRaw`).

(`convertFromRawToDraftState` is never used inside Draft itself, it's an end method).

**Comment by mitermayer** [comment]
The only problem with that is that we would trust the developer and they would be able to create data that they can deal with. Creating blocks that have nesting via block state, then if they select and paste and if on their definitions that block is not meant to be nested then it would break the editor

**Comment by mitermayer** [comment]
users would assume they can do all the operations with the rendered content therefore we should only allow to render the things we support.

**Comment by mitermayer** [comment]
I agree with the above points

**Comment by mitermayer** [comment]
Feel free to close this issue when you think this should be done already, feel free to remove the check there

**Comment by mitermayer** [comment]
Will close this issue, lets leave things as it is at the moment. We can revisit this later during cleaning up and when we have someone from facebook helping review the PR
