### ISSUE TITLE
Pressing enter ("split-block" command) should have a different behaviour when the block has nested children

### ISSUE THREAD

**Issue by SamyPesse** [mitermayer/draft-js#12]
Currently when pressing enter, we are splitting the block in 2 blocks of the same type.

But If we have a blockquote with some text and a nested list:
- Pressing Enter in the nested list, create a new list item (**Good!**)
- Pressing Enter in the blockquote text, split the blockquote and create another blockquote as top element (**Wrong!**)

I think that the `split-block` should do:

```
IF block has nested children
    create a new nested children of type "unstyled"
ELSE
    <current behaviour>
```

This can be achieved in [NestedUtils.handleKeyCommand](https://github.com/SamyPesse/draft-js/blob/feature/tree/src/model/modifier/NestedTextEditorUtil.js#L21).

**Comment by SamyPesse** [comment]
I've implemented a fix (https://github.com/SamyPesse/draft-js/commit/f4677ea91770ffd4587e119ddbacb0778f0dd2ce) but in fact, it's more tricky that I thought:

Let's consider a simple list item (it has a UNSTYLED block like it was told in #13):

```
UL_ITEM
     UNSTYLED
```

If my cursor is in the `UNSTYLED` block and I pressed enter, it will create a new UNSTYLED block:

```
UL_ITEM
     UNSTYLED
     UNSTYLED
```

Instead it should probably create a new nested list entry. This is related to #15 and can be fixed by the same solution.

EDIT: https://github.com/SamyPesse/draft-js/commit/371c08ade76cb5b884b363d5b5586c45d8b6ee6d is a start for this

**Comment by mitermayer** [comment]
what is the state of this issue @SamyPesse ?

**Comment by mitermayer** [comment]
@SamyPesse  please also check https://github.com/SamyPesse/draft-js/issues/20

**Comment by mitermayer** [comment]
thats done
