### ISSUE TITLE
blockRenderMap option to disable display of text in a block

### ISSUE THREAD

**Issue by SamyPesse** [mitermayer/draft-js#13]
For example for `table` / `table-row` / `table-cell`, we don't want to render the `block.text` using [_renderChildren](https://github.com/SamyPesse/draft-js/blob/feature/tree/src/component/contents/DraftEditorBlock.react.js#L219).

We can add an option `disableText` in `blockRenderMap` to disable this and only display the nested blocks.

Implementation is a 4 lines change.

@mitermayer What do you think?

**Comment by mitermayer** [comment]
Agree with that!

**Comment by mitermayer** [comment]
Maybe nested elements should have this set by default.  Other option is that all nested elements have a unstyled block as their children. this way they can style it

example 

all `li` would be `li -> p`

this would allow us to change the blocktype of the list item without breaking it out of the list
