### ISSUE TITLE
NestedUtils should provide a modifier version of defaultBlockRenderMap

### ISSUE THREAD

**Issue by SamyPesse** [mitermayer/draft-js#17]
I'm currently working on writing a first draft of the documentation. To make it easy to start with nesting, I think NestedUtils should provide a modified version of `defaultBlockRenderMap`: `NestedUtils.defaultBlockRenderMap`.

**Comment by SamyPesse** [comment]
@mitermayer I'm having some issue with the tree example when using:

``` js
const blockRenderMap = NestedUtils.DefaultBlockRenderMap;
```

Basically;
- It sometimes generate an unstyled block inside a unstyled block (it supposed to be prevent by the blockRenderMap)
- Table are now longer parsed.

I didn't commit the change in the tree example.

**Comment by mitermayer** [comment]
that is a great idea, will start looking into
- [x] - It sometimes generate an unstyled block inside a unstyled block (it supposed to be prevent by the blockRenderMap)
- [x] - Table are now longer parsed.
- [x] - Tree example should use NestedUtils.DefaultBlockRenderMap

**Comment by mitermayer** [comment]
all fixed
