### ISSUE TITLE
Clicking on UL when inside a OL should toggle block not create more nesting

### ISSUE THREAD

**Issue by mitermayer** [mitermayer/draft-js#25]
When clicking on wrapper elements and inside a wrapper we should just toggle block instead

**Comment by laktek** [comment]
Here's what currently happens in draft.js:

![list-current-draft](https://cloud.githubusercontent.com/assets/5358/15922748/b8454de6-2e6c-11e6-9b13-8da34c995cb7.gif)

This is how it behaves after tree structure changes:

![tree-struct](https://cloud.githubusercontent.com/assets/5358/15922765/d2ff76b6-2e6c-11e6-933b-d5ce95526dbb.gif)

We should retain the current behavior.

**Comment by mitermayer** [comment]
Will tackle this on https://github.com/SamyPesse/draft-js/issues/16 

Since I will create a separate ticket for the branch rebasing once I fix this first

**Comment by mitermayer** [comment]
this has been fixed on https://github.com/SamyPesse/draft-js/commit/9d94658e672696a56eb7addded90729f135a51f4
