### ISSUE TITLE
Weird behaviours on backspace

### ISSUE THREAD

**Issue by SamyPesse** [mitermayer/draft-js#29]
Backspace for nested content is not working as expected:

For this content:

```
A { type: 'list-item' }
A/1 {type: 'unstyled' }
A/2 {type: 'unstyled' }
```
- If I delete text in `A/2`, the cursor doesn't move to A/1, but stay on block after the list
- If I delete `A/2`, then try to remove `A/1`, it doesn't delete parent block `A`, instead it moves the cursor to the prev block.

@mitermayer I can work to fix this, but it might be a good idea that I do it in a separated branch, because I'm afraid we may have conflicting expectation for the final behaviour (similar to what happens when pressing Enter), you'll be able to review in a PR in this repo.

**Comment by mitermayer** [comment]
This was introduced with the wrong sorting algorithmn, please check again with master it should be working now
