### ISSUE TITLE
convertFromDraftStateToRaw should also support tree nested elements

### ISSUE THREAD

**Issue by mitermayer** [mitermayer/draft-js#3]
## Background

convertFromDraftStateToRaw should also now support tree nested elements so that data can be persisted. It should do so by making sure that does not break backwards compatibility allowing data to still be saved as flat structure.
## Actions
- [ ] convertFromDraftStateToRaw should have an optional parameter **'enableNesting'*** configuration flag and when creating the ContentBlocks will generate the correct nesting keys `foo/bar`, `foo/foo`, `foo` for contentBlocks that have nested elements
- [ ] Add tests, we should make sure that convertFromDraftStateToRaw behaves as normal when the  **'enableNesting'*** is disabled
- [ ]  Add tests, we should make sure that convertFromDraftStateToRaw behaves as expected when the  **'enableNesting'*** is enabled

\* We still do not have such feature implemented https://github.com/SamyPesse/draft-js/issues/4

**Comment by SamyPesse** [comment]
@mitermayer 

I've started this: https://github.com/SamyPesse/draft-js/commit/e1cb7e9a09158fde91812e41736b6ae379b8ee91

This is the cleaner solution (`convertBlockFromDraftToRaw` is defined inside `convertFromDraftStateToRaw`), but it avoid complex function signatures.

Also the `block.key` is the relative key, not the absolute one, so that:

``` js
convertFromRawToDraft(convertFromDraftToRaw(contentState)) == contentState
```

But it also means:

``` js
var raw = convertFromDraftToRaw(contentState);

contentState.getBlockForKey(raw.blocks[0].blocks[0].key) === undefined
```

**Comment by SamyPesse** [comment]
I'm not sure the `enableNesting` is required.

**Comment by mitermayer** [comment]
@SamyPesse how would we solve the pasting without enableNesting ? since it would come as html format, we would need a wat to identify if the data pasted should be flattened or nested

Or do you mean we don't need `enableNesting` for this issue ?

**Comment by SamyPesse** [comment]
Yes I mean "for this issue", `convertFromDraftToRaw` is not used in pasting, right ?

I agree that we need this option for the HTML and pasting.

**Comment by mitermayer** [comment]
is the only remaining tasks on this issue adding tests ?

**Comment by mitermayer** [comment]
Sorry for the confusion all the above comments make sense was thinking of this issue as convertFromRawToDraftState sorry for the confusion
